### ISSUE TITLE
dbCAN now dbCAN2?

### ISSUE THREAD

**Issue by hyphaltip** [cjneely10/MetaSanity#1]
link to dbCAN is invalid - new website is http://bcb.unl.edu/dbCAN2/

**Comment by cjneely10** [comment]
Thank you for your message

The current URL in the download script is 
http://bcb.unl.edu/dbCAN2/download/dbCAN-HMMdb-V8

**Comment by cjneely10** [comment]
The URL should be valid, so I will close this issue. Feel free to reach out if you have any additional comments.
