### ISSUE TITLE
pplacer error?

### ISSUE THREAD

**Issue by camillaln** [cjneely10/MetaSanity#2]
Hi,
I am having problems with pplacer. Do you have any advice as to how I can solve this?

I am getting this error from gtdbtk:
[2019-10-08 17:48:28] INFO: Placing 40 archaeal genomes into reference tree with pplacer (be patient).
[2019-10-08 17:48:33] ERROR: An error was encountered while running pplacer.
[2019-10-08 17:48:33] ERROR: Controlled exit resulting from an unrecoverable error or warning.

================================================================================
EXCEPTION: PplacerException
  MESSAGE: 
________________________________________________________________________________

Traceback (most recent call last):
  File "/usr/local/bin/gtdbtk", line 452, in <module>
    gt_parser.parse_options(args)
  File "/usr/local/lib/python2.7/dist-packages/gtdbtk/main.py", line 602, in parse_options
    self.classify(options)
  File "/usr/local/lib/python2.7/dist-packages/gtdbtk/main.py", line 415, in classify
    options.debug)
  File "/usr/local/lib/python2.7/dist-packages/gtdbtk/classify.py", line 320, in run
    scratch_dir)
  File "/usr/local/lib/python2.7/dist-packages/gtdbtk/classify.py", line 146, in place_genomes
    pplacer.run(self.cpus, 'WAG', pplacer_ref_pkg, pplacer_json_out, user_msa_file, pplacer_out, pplacer_mmap_file)
  File "/usr/local/lib/python2.7/dist-packages/gtdbtk/external/pplacer.py", line 61, in run
    raise PplacerException(proc_err)
PplacerException
================================================================================

It is still running CheckM.

My command was:
python3 /Users/camilla/doodle/cheers2019/MetaSanity/MetaSanity.py -c PhyloSanity.ini -d dereplicated_genomes/ -o PhylosanityTest -b SynbiomicsMAGs PhyloSanity 2>eval.log

Thanks for any help with this. Its my first attempt to use docker - so I might have something set up completely wrong.

Camilla

**Comment by cjneely10** [comment]
Thank you for your message Camilla,

`pplacer` can run into several runtime issues, depending on the situation. [This issue post](https://github.com/Ecogenomics/GTDBTk/issues/170) describes a few of the things that could have gone wrong in this step. The most common culprit is due to memory allocation issues. How many threads were you using?

**Comment by camillaln** [comment]
Thanks for getting back to me. It says it is running gtdbtk with just 1 thread. I tried the test dataset as well and got the same error. I am running it on my Mac so perhaps its just too small - I will try it on our server instead.

**Comment by cjneely10** [comment]
Glad to help,

Assuming your Mac a personal computer, GTDB-Tk will not work. It requires >100 GB of RAM to complete its run, regardless of the numbers of genomes. CheckM has similarly high memory requirements, although the `--reduced_tree` flag in the PhyloSanity.ini config file drops this down to about 16-20 GB.

PhyloSanity is best run on servers, or personal computers with a minimum of 16-20 GB or RAM.

**Comment by cjneely10** [comment]
I will go ahead and close this issue, as it relates to system requirements for MetaSanity and not an actual bug/issue in the code.

Feel free to reach out if you have any additional comments/concerns.

Have a great day.
