### ISSUE TITLE
Docker installation

### ISSUE THREAD

**Issue by vinisalazar** [cjneely10/MetaSanity#3]
Hi,

thank you for providing this package. I'm excited to use it.

In the wiki page, you recommend that the software should be installed by the Docker image. Should the install.py script be the only way to install from Docker? Can it not be pulled directly from DockerHub?

Having this in mind, I'd suggest two things:
- adding the DockerHub link to the install instructions and more instructions on how to run from Docker.
- adding the Dockerfile to the GitHub repo and integrating both repositories (enabling automated builds).

If you are interested, I'd be happy to assist with these and also by providing an end-user POV.

Kind regards,

V

**Comment by vinisalazar** [comment]
> - adding the DockerHub link to the install instructions and more instructions on how to run from Docker.

When I try to run the standalone Docker image with `docker run -it <image-id>`, I get the following error: `pipedm.py: error: the following arguments are required: program, -d/--directory, -c/--config_file`

I assume calling the Docker image runs this script, but it needs these parameters. It would be great to be able to run the image in interactive mode and run everything from inside the container.

**Comment by cjneely10** [comment]
Good afternoon,

Thank you for your message.
The [Installation wiki page](https://github.com/cjneely10/MetaSanity/wiki/2-Installation) can walk you through a full installation. The `install.py` script will download the docker image and all required scripts/config files, and the `download-data.py` script will pull down all needed data.

The script `MetaSanity.py` will run your version of MetaSanity - e.g., it will run the docker image, or run the source code. See the [usage wiki](https://github.com/cjneely10/MetaSanity/wiki/3-Usage) for more info. Using `MetaSanity.py` will the error that you listed above. 

That being said, I will add an option to allow users to run this image in interactive mode.

**Comment by vinisalazar** [comment]
> That being said, I will add an option to allow users to run this image in interactive mode.

￼￼that will be a very welcome feature!

**Comment by cjneely10** [comment]
Good morning,

I was unable to incorporate your request into today's release of v1.1, but I have this feature slated for a future update. I will close out this issue in the meantime.
