### ISSUE TITLE
Exploring amino acid/vitamin biosynthetic pathways

### ISSUE THREAD

**Issue by elizabethmcd** [cjneely10/MetaSanity#5]
Hi, great tool! This might be more of a general KofamKOALA/KO database question. If I'm interpreting how MetaSanity outputs functional information, it gives pathway summaries for major carbon/biogeochemical pathways, correct? Is there a way to investigate amino acid and vitamin biosynthesis pathways using MetaSanity, or alternatively do you know if the KO database has a good listing of KO terms/modules to view amino acid pathways to then explore within KofamKOALA?

**Comment by cjneely10** [comment]
Thank you, I hope you find this software suite useful in your research.

MetaSanity incorporates a tool called [KEGG-Decoder](https://github.com/bjtully/BioData) that provides summary info for major carbon/biogeochemical pathways. The author recently released an update that includes additional pathways, including amino acids and some vitamin biosynthesis. Step Two of the [wiki page](https://github.com/cjneely10/MetaSanity/wiki/2-Installation) provides some details for updating to the most current version of MetaSanity, which includes his update.

Feel free to contact again if you have any additional questions.
